; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.tensor.g2s.tile.1d(ptr addrspace(7), ptr addrspace(3), ptr, i32, i16, i64, i1, i1, i32) #0

define void @probe_cp_async_bulk_tensor_1d_g2s(ptr %dst_generic, ptr %barrier_generic, ptr %tensor_map, i32 %coord0) #0 {
  %dst = addrspacecast ptr %dst_generic to ptr addrspace(7)
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  call void @llvm.nvvm.cp.async.bulk.tensor.g2s.tile.1d(ptr addrspace(7) %dst, ptr addrspace(3) %barrier, ptr %tensor_map, i32 %coord0, i16 0, i64 0, i1 false, i1 false, i32 0) #0
  ret void
}

attributes #0 = { convergent }
