; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare double @llvm.nvvm.fma.rm.d(double, double, double)

define double @probe_fma_rm_f64(double %arg0, double %arg1, double %arg2) {
  %result = call double @llvm.nvvm.fma.rm.d(double %arg0, double %arg1, double %arg2)
  ret double %result
}
