; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32, i64)

define { i32, i1 } @probe_match_all_i64_sync_rr(i32 %member_mask, i64 %value) {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 %member_mask, i64 %value)
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_match_all_i64_sync_ri(i64 %value) {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 -1, i64 %value)
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_match_all_i64_sync_ir(i32 %member_mask) {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 %member_mask, i64 7)
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_match_all_i64_sync_ii() {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 -1, i64 7)
  ret { i32, i1 } %result
}
