; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i1 @probe_mbarrier_test_wait(ptr %barrier_generic, i64 %token) #0 {
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %result_i32 = call i32 asm sideeffect "{ .reg .pred %p0; mbarrier.test_wait.shared.b64 %p0, [$1], $2; selp.b32 $0, 1, 0, %p0; }", "=r,l,l,~{memory}"(ptr addrspace(3) %barrier, i64 %token) #0
  %result = trunc i32 %result_i32 to i1
  ret i1 %result
}

attributes #0 = { convergent }
