; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define { i32, i32 } @probe_mma_m8n8k16_s32_s8(i32 %c0, i32 %c1, i32 %a0, i32 %b0) #0 {
  %result = call { i32, i32 } asm sideeffect "mma.sync.aligned.m8n8k16.row.col.s32.s8.s8.s32 {$0, $1}, {$4}, {$5}, {$2, $3};", "=r,=r,r,r,r,r"(i32 %c0, i32 %c1, i32 %a0, i32 %b0) #0
  ret { i32, i32 } %result
}

attributes #0 = { convergent }
