; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define { i32, i32, i32, i32 } @probe_mma_m16n8k64_s32_u4_s4_satfinite(i32 %c0, i32 %c1, i32 %c2, i32 %c3, i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %b0, i32 %b1) #0 {
  %result = call { i32, i32, i32, i32 } asm sideeffect "mma.sync.aligned.m16n8k64.row.col.satfinite.s32.u4.s4.s32 {$0, $1, $2, $3}, {$8, $9, $10, $11}, {$12, $13}, {$4, $5, $6, $7};", "=r,=r,=r,=r,r,r,r,r,r,r,r,r,r,r"(i32 %c0, i32 %c1, i32 %c2, i32 %c3, i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %b0, i32 %b1) #0
  ret { i32, i32, i32, i32 } %result
}

attributes #0 = { convergent }
