; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.shfl.sync.up.i32(i32, i32, i32, i32)

define i32 @probe_shuffle_up_sync_rr(i32 %member_mask, i32 %value, i32 %lane) {
  %result = call i32 @llvm.nvvm.shfl.sync.up.i32(i32 %member_mask, i32 %value, i32 %lane, i32 0)
  ret i32 %result
}
define i32 @probe_shuffle_up_sync_ri(i32 %value, i32 %lane) {
  %result = call i32 @llvm.nvvm.shfl.sync.up.i32(i32 -1, i32 %value, i32 %lane, i32 0)
  ret i32 %result
}
define i32 @probe_shuffle_up_sync_ir(i32 %member_mask, i32 %value) {
  %result = call i32 @llvm.nvvm.shfl.sync.up.i32(i32 %member_mask, i32 %value, i32 1, i32 0)
  ret i32 %result
}
define i32 @probe_shuffle_up_sync_ii(i32 %value) {
  %result = call i32 @llvm.nvvm.shfl.sync.up.i32(i32 -1, i32 %value, i32 1, i32 0)
  ret i32 %result
}
