; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.ld.16x64b.x1; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_ld_16x64b_x1_pack16(i32 %tmem) #0 {
  %result = call i32 asm sideeffect "tcgen05.ld.sync.aligned.16x64b.x1.pack::16b.b32 {$0}, [$1];", "=r,r,~{memory}"(i32 %tmem) #0
  ret void
}

attributes #0 = { convergent }
