; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.16x64b.x8; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_16x64b_x8_raw(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.16x64b.x8.b32 [$0], {$1,$2,$3,$4,$5,$6,$7,$8};", "r,r,r,r,r,r,r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7) #0
  ret void
}

attributes #0 = { convergent }
