; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.cp.128x256b.b6x16_p32.cg1; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_cp_128x256b_b6x16_p32(i32 %tmem, i64 %desc) #0 {
  call void asm sideeffect "tcgen05.cp.cta_group::1.128x256b.b8x16.b6x16_p32 [$0], $1;", "r,l,~{memory}"(i32 %tmem, i64 %desc) #0
  ret void
}

attributes #0 = { convergent }
