; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1f72d053300ad70672b9cf851743dd05e0904f7222828eecd53d5ca88a4a0088.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.cp.64x128b_warpx2_01_23.b4x16_p64.cg2; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_cp_64x128b_warpx2_01_23_b4x16_p64_cg2(i32 %tmem, i64 %desc) #0 {
  call void asm sideeffect "tcgen05.cp.cta_group::2.64x128b.warpx2::01_23.b8x16.b4x16_p64 [$0], $1;", "r,l,~{memory}"(i32 %tmem, i64 %desc) #0
  ret void
}

attributes #0 = { convergent }
